### ISSUE TITLE
Add exponential backoff strategy

### ISSUE THREAD

**Issue by itsJoKr** [GetStream/rate_limiter#5]
Very common strategy when you don't want the user to spam some action. Probably a first association when someon says rate limiting:

https://en.wikipedia.org/wiki/Exponential_backoff#Rate_limiting

Is it possible to implement this?

**Comment by xsahil03x** [comment]
Hey @itsJoKr, Added in https://github.com/GetStream/rate_limiter/releases/tag/1.0.0 🎉
